### ISSUE TITLE
RPerl on OpenBSD

### ISSUE THREAD

**Issue by aprokopyev** [wbraswell/rperl#106]
Please let me know is it possible to use RPerl on OpenBSD or at least target it from the compiler on Linux ?

**Comment by wbraswell** [comment]
Yes you should be able to use RPerl on OpenBSD or any other operating system with access to GCC or a compatible C++14 compiler.  However, installing RPerl from scratch is quite complicated, so for simplicity I strongly suggest you use our official RPerl Docker image, based on Debian Linux.
``docker run -it wbraswell/rperl_cpan``
http://rperl.org/get_rperl.html

For now I will leave this issue open, in case you experience actual problems running in OpenBSD.

What are your goals for using RPerl?

**Comment by aprokopyev** [comment]
In the future I may need Perl language for making simple scripts for automation.
And I may need RPerl to temporary protect script source from viewing before payment.
Would it work as described?

**Comment by wbraswell** [comment]
Yes, RPerl will give you strong protection of your Perl source code, as well as speed optimization.  You must use low-magic Perl code in order to gain the performance optimization of RPerl.  If you only want to protect your Perl source code, with no need for significant speed increase, then I suggest the Reini Urban's B::C compiler AKA perlcc instead.
https://metacpan.org/release/B-C
