### ISSUE TITLE
Perl scripts without ".pl" extension

### ISSUE THREAD

**Issue by trizen** [wbraswell/rperl#19]
Please let RPerl to execute Perl scripts even when they don't have an extension.

Currently, it dies with the following error:
```
$ rperl x
ERROR EARG05: Specified RPerl source code input file 'x' is not a Perl program ending in '.pl' or module ending in '.pm', dying
```

**Comment by wbraswell** [comment]
This is not a good idea, because the default behavior is to take input file "foo.pl" and output compiled file "foo".  A special case could be made to work around this by using the "--outfile=bar" option which could take input file "foo.pl" and compile to output file "bar".  Then I would need to create additional logic allowing just "foo" as an input file, which I don't like because it is messy and not straightforward and does not follow the RPerl optimization philosophy of "There Is One Way To Do It".
...
Can you please provide me with a strong reason why you MUST have input file "foo" instead of "foo.pl"?

**Comment by trizen** [comment]
Fair enough. It's not a big issue, but sometimes we may find Perl scrips which don't have extensions, such as `/usr/bin/automake`.

**Comment by wbraswell** [comment]
We can re-open the issue when we get far enough to be able to compile `automake`.  :-)

**Comment by trizen** [comment]
Ok. :-)
