### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Azq2** [wbraswell/rperl#20]
make test failed, until i installed some packages:

File::Copy::Recursive
IO::All
Parse::RecDescent
Pegex
Regexp
Test::Warn

Please, add it to Makefile.PL

**Comment by wbraswell** [comment]
@Azq2 
This must be an issue with your system, because those packages you have listed are already sub-dependencies of packages which are listed in Makefile.PL.
For example, both Parse::RecDescent and Pegex asre dependencies of Inline::C, which is in Makefile.PL.
https://metacpan.org/pod/distribution/Inline-C/lib/Inline/C.pod

So, I'm going to mark this issue as "Closed".  If you can find bugs in Inline::C or some other RPerl dependencies, then please come back here and let me know and we can file the appropriate bug reports to the proper package maintainers.  Thanks!
